[package]
name = "ezocr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0.115"
pkg-config = "0.3.28"

[build-dependencies]
cxx-build = "1.0.115"
pkg-config = "0.3.28"
