[workspace]
resolver = "2"
members = [
	"crates/*",
  "apps/desktop/src-tauri",
]

[workspace.package]
license = "MIT"
edition = "2021"
repository = "https://github.com/eamesh/ezocr"

[workspace.dependencies]
tracing = "0.1.40"
tokio = "1.35.1"
